/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tennis_court_animation.glb
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tennis-court-animation-fab5950b1b6f441da6a73c314f0cd04e
Title: Tennis Court (Animation)
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TennisCourt(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/tennis_court_animation.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.play());
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Tennis_CourtFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Tennis_Ball"
                  position={[-206.887, 58.706, 15.176]}
                  rotation={[0.698, 0, 0]}
                  scale={[0.035, 0.034, 0.035]}
                >
                  <mesh
                    name="Tennis_Ball_09_-_Default_0"
                    geometry={nodes["Tennis_Ball_09_-_Default_0"].geometry}
                    material={materials["09_-_Default"]}
                  />
                </group>
                <group
                  name="Tennis_Racketzz"
                  position={[-218.055, 66.724, 19.293]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.034, 0.048, 0.022]}
                >
                  <mesh
                    name="Tennis_Racketzz_03_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz_03_-_Default_0"].geometry
                    }
                    material={materials["03_-_Default_0"]}
                  />
                  <mesh
                    name="Tennis_Racketzz_02_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz_02_-_Default_0"].geometry
                    }
                    material={materials["02_-_Default_0"]}
                  />
                  <mesh
                    name="Tennis_Racketzz_07_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz_07_-_Default_0"].geometry
                    }
                    material={materials["07_-_Default_0"]}
                  />
                </group>
                <group
                  name="Tennis_Racketzz001"
                  position={[228.025, 66.724, -44.562]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.034, 0.048, 0.022]}
                >
                  <mesh
                    name="Tennis_Racketzz001_03_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz001_03_-_Default_0"].geometry
                    }
                    material={materials["03_-_Default_0"]}
                  />
                  <mesh
                    name="Tennis_Racketzz001_02_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz001_02_-_Default_0"].geometry
                    }
                    material={materials["02_-_Default_0"]}
                  />
                  <mesh
                    name="Tennis_Racketzz001_07_-_Default_0"
                    geometry={
                      nodes["Tennis_Racketzz001_07_-_Default_0"].geometry
                    }
                    material={materials["07_-_Default_0"]}
                  />
                </group>
                <group
                  name="Court"
                  position={[0, -6.623, 6.623]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Court_08_-_Default_0"
                    geometry={nodes["Court_08_-_Default_0"].geometry}
                    material={materials["08_-_Default"]}
                  />
                  <mesh
                    name="Court_01_-_Default_0"
                    geometry={nodes["Court_01_-_Default_0"].geometry}
                    material={materials["01_-_Default"]}
                  />
                </group>
                <group
                  name="Net"
                  position={[0.181, -34.999, 6.861]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.078, 1, 0.846]}
                >
                  <mesh
                    name="Net_02_-_Default_0"
                    geometry={nodes["Net_02_-_Default_0"].geometry}
                    material={materials["02_-_Default"]}
                  />
                  <mesh
                    name="Net_03_-_Default_0"
                    geometry={nodes["Net_03_-_Default_0"].geometry}
                    material={materials["03_-_Default"]}
                  />
                  <mesh
                    name="Net_07_-_Default_0"
                    geometry={nodes["Net_07_-_Default_0"].geometry}
                    material={materials["07_-_Default"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/tennis_court_animation.glb");
